--- #This playbook is not supposed to work corectly => Strange interaction between ansible et nohup 
- name: Play to copy and execute 'main' binary
  become: true
  hosts: all
  remote_user: micka
  tasks:
  - name: Copy bin with owner and permissions
    copy:
      src: /home/micka/Documents/api-go/aws-ansible/main
      dest: ./main
      owner: root
      group: root
      mode: '0777'
  - name: cp .aws folder
    copy:
      src: /home/micka/.aws
      dest: /home/ec2-user
      owner: root
  - name: Clean port
    command: "echo $HOME" #"fuser -k 8000/tcp"
  - name: Execute my bin in detach
    shell: "nohup ./main &"
  # Test ALA RACHE
  - name: "Get url"
    uri:
      url: http://15.237.94.21:8000/
      method: GET
      force_basic_auth: yes
      status_code: 200
    register: http_response
  - name: Verify appli output
    assert:
      that:
        - http_response.status == 200
      fail_msg: "Wrong answer from server, is it running?"
      success_msg: "all ok"
